import type { Certificate } from "../types/CertificateType";

import {
    bills,
    certHt,
    cssInter,
    dgrid,
    fullStack,
    ifrn,
    jsNode,
    jsV,
    jsVI,
    pEngi,
    reactBonus,
    zero,
} from '../utils/CertificadosExport';

export const certificados: Certificate[] = [
    {
        id: "0",
        title: "Téc. Informática",
        photo: ifrn,
        school: "IFRN",
        description: "Curso Técnico em Informática pelo IFRN - Campus Caicó.",
        duration: "2020 - 2024",
        status: true,
        skills: "Lógica de Programação, SQL, Front End, Back End, API REST",
        discriminator: 'certificate',
        photoCollection: [ifrn],
    },
    {
        id: "1",
        title: "Prog. com I.A",
        school: "DevClub",
        photo: zero,
        description: "Curso de Programação com Inteligência Artificial.",
        duration: "2026",
        skills: "Engenharia de Prompt",
        status: true,
        discriminator: 'certificate',
        photoCollection: [zero],
    },
    {
        id: "2",
        title: "Prog. FullStack",
        school: "DevClub",
        photo: fullStack,
        description: "Formação Full Stack pela DevClub.",
        duration: "2026",
        skills: "HTML, CSS, JS, Node, React, NoSQL",
        status: true,
        discriminator: 'certificate',
        photoCollection: [fullStack],
    },
    {
        id: "3",
        title: "Formação em Engenharia de Prompt",
        school: "DevClub",
        photo: pEngi,
        description: "Formação voltada para criação e otimização de prompts para IA.",
        duration: "2026",
        status: true,
        skills: "Engenharia de Prompt,",
        discriminator: 'certificate',
        photoCollection: [pEngi],
    },
    {
        id: "4",
        title: "TypeScript",
        school: "DevClub",
        photo: bills,
        description: "Curso de TypeScript.",
        duration: "2026",
        status: true,
        discriminator: 'certificate',
        photoCollection: [bills],
    },
    {
        id: "5",
        title: "HTML - Front End Club",
        school: "DevClub",
        photo: certHt,
        description: "Fundamentos de HTML para desenvolvimento web.",
        duration: "2026",
        status: false,
        discriminator: 'certificate',
        photoCollection: [certHt],
    },
    {
        id: "6",
        title: "CSS Intermediário",
        school: "DevClub",
        photo: cssInter,
        description: "Conceitos intermediários de CSS.",
        duration: "2026",
        status: false,
        discriminator: 'certificate',
        photoCollection: [cssInter],
    },
    {
        id: "7",
        title: "CSS - Display GRID",
        school: "DevClub",
        photo: dgrid,
        description: "Construção de layouts utilizando CSS Grid.",
        duration: "2026",
        status: false,
        discriminator: 'certificate',
        photoCollection: [dgrid],
    },
    {
        id: "8",
        title: "JavaScript pt. V - A Nova Ordem de Dados",
        school: "DevClub",
        photo: jsV,
        description: "Módulo avançado de JavaScript.",
        duration: "2026",
        status: false,
        discriminator: 'certificate',
        photoCollection: [jsV],
    },
    {
        id: "9",
        title: "JavaScript pt. VI - A Ascensão do Async_Await",
        school: "DevClub",
        photo: jsVI,
        description: "Programação assíncrona com Async/Await.",
        duration: "2026",
        status: false,
        discriminator: 'certificate',
        photoCollection: [jsVI],
    },
    {
        id: "10",
        title: "Node",
        school: "DevClub",
        photo: jsNode,
        description: "Desenvolvimento backend com Node.js.",
        duration: "2026",
        status: false,
        discriminator: 'certificate',
        photoCollection: [jsNode],
    },
    {
        id: "11",
        title: "React pt.3 - Bônus - DevClub Full Stack",
        school: "DevClub",
        photo: reactBonus,
        description: "Conteúdo bônus avançado de React.",
        duration: "2026",
        status: false,
        discriminator: 'certificate',
        photoCollection: [reactBonus],
    },
];