import type { Project } from "../types/ProjectsType";
import { cep, clima, pesquisarPerfilGithub, photosAdvogado, photosAutocenter, photosBelezza, photosClinicaNutricao, photosConsultorioOdonto, photosEliteFitness, photosHair, topdog } from "../utils/ProjetosExport";
import { gerador } from "../utils/ProjetosExport";

export const projects: Project[] =
    [
        {
            id: "0",
            title: "TopDog",
            photo: topdog,
            description: "Sistema de gerenciamento de pedidos da HotDogueria TopDog ",
            demo: "",
            github: "https://github.com/gabriel360p/topdog-frontend",
            badge: "Javascript,TypeScript,Tailwind",
            duration: "2 meses",
            status: false,
            discriminator: 'project',
        },
        {
            id: "5",
            title: "Odonto Sorriso",
            photo: photosConsultorioOdonto[0],
            photoCollection: photosConsultorioOdonto,
            description: "Landing page do consultório Odonto Sorriso. ",
            demo: "https://demo-consultorio-odonto.vercel.app",
            github: "https://github.com/gabriel360p/demo-consultorio-odonto.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            functions: ['Gerar senhas aleatórias', 'Copiar senha criada', 'Definir tamanho da senha'],
            desafios: "O Maior desafio foi fazer as animações do jeito que eu queria.",
            status: true,
            discriminator: 'project',
        },
        {
            id: "6",
            title: "Belezza Estética",
            photo: photosBelezza[0],
            photoCollection: photosBelezza,
            description: "Landing page da Belezza Estética. ",
            demo: "https://clinica-belezza-demo.vercel.app/",
            github: "https://github.com/gabriel360p/demo-clinica-estetica.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            status: true,
            discriminator: 'project',
        },
        {
            id: "7",
            title: "Auto Center Premium",
            photo: photosAutocenter[0],
            photoCollection: photosAutocenter,
            description: "Landing page da Auto Center Premium. ",
            demo: "https://vercel.com/gabriel360ps-projects/demo-auto-center-premium",
            github: "https://github.com/gabriel360p/demo-auto-center-premium.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            status: true,
            discriminator: 'project',
        },
        {
            id: "8",
            title: "Clínica Médica",
            photo: photosClinicaNutricao[0],
            photoCollection: photosClinicaNutricao,
            description: "Landing page de uma clínica de nutrição. ",
            demo: "https://demo-clinica-nutricao.vercel.app/",
            github: "https://github.com/gabriel360p/demo-clinica-medica.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            status: true,
            discriminator: 'project',
        },
        {
            id: "9",
            title: "Academia Elite Fitness",
            photo: photosEliteFitness[0],
            photoCollection: photosEliteFitness,
            description: "Landing page da academia Elite Fitness. ",
            demo: "https://demo-elite-fitness.vercel.app/",
            github: "https://github.com/gabriel360p/demo-elite-fitness.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            status: true,
            discriminator: 'project',
        },
        {
            id: "10",
            title: "Escritório Oliveira & Associados",
            photo: photosAdvogado[0],
            description: "Landing page do Escritório Oliveira & Associados ",
            photoCollection: photosAdvogado,
            demo: "https://demo-escritorio-oliveira-associados.vercel.app/",
            github: "https://github.com/gabriel360p/demo-escritorio-oliveira-associados.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            status: true,
            discriminator: 'project',
        },
        {
            id: "1011",
            title: "Patinhas Pet Shop & Vet",
            photo: photosAdvogado[0],
            description: "Landing page da Patinhas Pet Shop & Vet",
            photoCollection: photosAdvogado,
            demo: "https://demo-patinhas-petshop.vercel.app/",
            github: "https://github.com/gabriel360p/demo-patinhas-petshop.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            status: true,
            discriminator: 'project',
        },
        {
            id: "11",
            title: "Studio Hair & Beauty",
            photo: photosHair[0],
            description: "Landing page da Studio Hair & Beauty",
            photoCollection: photosHair,
            demo: "https://demo-studio-hair-beaty.vercel.app/",
            github: "https://github.com/gabriel360p/demo-studio-hair-beaty.git",
            badge: "Javascript,CSS,HTML",
            // duration: "",
            status: true,
            discriminator: 'project',
        },
        {
            id: "1",
            title: "Gerador de Senhas",
            photo: gerador,
            description: "Gerador de senhas seguras e aleatórias",
            demo: "https://gerador-de-senhas-seguras-react.vercel.app/",
            github: "https://github.com/gabriel360p/gerador-de-senhas.git",
            badge: "Javascript,Styled-Components",
            duration: "1 dia",
            status: true,
            discriminator: 'project',
        },
        {
            id: "2",
            title: "Clima Agora",
            photo: clima,
            description: "Veja as informações do clima agora mesmo",
            demo: "https://clima-agora-react.vercel.app/",
            github: "https://github.com/gabriel360p/clima-app-react.git",
            badge: "Javascript,OpenWeatherMap API",
            duration: "1 dia",
            status: true,
            discriminator: 'project',
        },
        {
            id: "3",
            title: "Busca Cep",
            photo: cep,
            description: "Veja suas informações de endereço agora mesmo",
            demo: "https://buscadordecep-react.vercel.app/ ",
            github: "https://github.com/gabriel360p/react-cep-form-autocomplete.git",
            badge: "Javascript,ViaCep API",
            duration: "1 dia",
            status: true,
            discriminator: 'project',
        },
        {
            id: "4",
            title: "Buscador de perfil do Github",
            photo: pesquisarPerfilGithub,
            description: "Veja informações de perfis do github",
            demo: "https://buscador-perfil-github.vercel.app/",
            github: "https://github.com/gabriel360p/github-search-react.git",
            badge: "Javascript,GitHub API",
            duration: "1 dia",
            status: true,
            discriminator: 'project',
        },
    ]
