import type { Project } from "../types/ProjectsType";
import { topdog } from "../utils/ProjetosExport";

export const projects:Project[]=
[
    {   
        id:"0",
        title:"TopDog",
        photo:topdog,
        description:"Sistema de gerenciamento de pedidos da HotDogueria TopDog ",
        demo:"",
        github:"https://github.com/gabriel360p/topdog-frontend",
        badge:"Javascript,TypeScript,Tailwind",
        duration:"2 meses",
        status:false,
    },
    {   
        id:"1",
        title:"TopDog",
        photo:topdog,
        description:"Sistema de gerenciamento de pedidos da HotDogueria TopDog ",
        demo:"",
        github:"https://github.com/gabriel360p/topdog-frontend",
        badge:"Javascript,TypeScript,Tailwind",
        duration:"2 meses",
        status:false,
    },
    {   
        id:"2",
        title:"TopDog",
        photo:topdog,
        description:"Sistema de gerenciamento de pedidos da HotDogueria TopDog ",
        demo:"",
        github:"https://github.com/gabriel360p/topdog-frontend",
        badge:"Javascript,TypeScript,Tailwind",
        duration:"2 meses",
        status:false,
    },
    {   
        id:"3",
        title:"TopDog",
        photo:topdog,
        description:"Sistema de gerenciamento de pedidos da HotDogueria TopDog ",
        demo:"",
        github:"https://github.com/gabriel360p/topdog-frontend",
        badge:"Javascript,TypeScript,Tailwind",
        duration:"2 meses",
        status:false,
    },
    {   
        id:"4",
        title:"TopDog",
        photo:topdog,
        description:"Sistema de gerenciamento de pedidos da HotDogueria TopDog ",
        demo:"",
        github:"https://github.com/gabriel360p/topdog-frontend",
        badge:"Javascript,TypeScript,Tailwind",
        duration:"2 meses",
        status:false,
    },
    {   
        id:"5",
        title:"TopDog",
        photo:topdog,
        description:"Sistema de gerenciamento de pedidos da HotDogueria TopDog ",
        demo:"",
        github:"https://github.com/gabriel360p/topdog-frontend",
        badge:"Javascript,TypeScript,Tailwind",
        duration:"2 meses",
        status:false,
    },
]